export default {
  title: "Solomon Nyamson",
  description:
    "A passionate Data Scientist, Research Fellow and Web Developer.",
  image: "/assets/images/author.jpg",
  url: "https://solomonnyamson.vercel.app",
  keywords: [
    "Solomon",
    "Solomon Nyamson",
    "@snyamson",
    "snyamson",
    "Portfolio",
    "Solomon Portfolio ",
    "Solomon Nyamson Portfolio",
    "data scientist",
    "data analyst",
    "machine learning",
    "excel",
    "tableau",
    "full stack web developer",
    "web developer",
    "nextjs",
    "nodejs ",
    "expressjs",
    "reactjs ",
    "contextapi",
  ],
};
