/* eslint-disable @next/next/no-css-tags */
import Document, { Html, Head, Main, NextScript } from "next/document";

class MyDocument extends Document {
  static async getInitialProps(ctx) {
    const initialProps = await Document.getInitialProps(ctx);
    return { ...initialProps };
  }

  render() {
    return (
      <Html>
        <Head>
          <meta name="description" content="Generated by create next app" />
          <meta charSet="utf-8" />

          {/* Favicon  */}

          <link rel="icon" href="/favicon.ico" />

          {/* Libraries Stylesheet  */}

          <link rel="stylesheet" href="../assets/css/main.css" />
          <noscript>
            <link rel="stylesheet" href="../assets/css/noscript.css" />
          </noscript>

          {/* JavaScript Libraries  */}

          <script async src="../assets/js/jquery.min.js"></script>
          <script async src="../assets/js/jquery.scrolly.min.js"></script>
          <script async src="../assets/js/jquery.scrollex.min.js"></script>
          <script async src="../assets/js/browser.min.js"></script>
          <script async src="../assets/js/breakpoints.min.js"></script>
          <script async src="../assets/js/util.js"></script>

          {/* Javascript  */}
          <script async src="../assets/js/main.js"></script>
        </Head>
        <body className="is-preload">
          <Main />
          <NextScript />
        </body>
      </Html>
    );
  }
}

export default MyDocument;
