/* eslint-disable @next/next/no-img-element */
import Head from "next/head";
import groq from "groq";
import client from "../client";
import About from "../components/about";
import Banner from "../components/banner";
import Contact from "../components/contact";
import Tiles from "../containers/tiles";

export default function Home({ aboutMe, resume }) {
  return (
    <>
      <Head>
        <title>Home | S - N Portfolio</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Banner resume={resume} />
      <Tiles />
      <About about={aboutMe} />
      <Contact />
    </>
  );
}

export async function getStaticProps() {
  const aboutMe = await client.fetch(groq`
      *[_type == "aboutMe"]
      {
        description,
      }
    `);

  const resume = await client.fetch(groq`
      *[_type == "resume"]
      {
        "resumeUrl": resumeDoc.asset->url,
      }
    `);

  return {
    props: {
      aboutMe,
      resume,
    },
  };
}
