import Head from "next/head";
import groq from "groq";
import client from "../client";
import About from "../components/about";
import Banner from "../components/banner";
import Contact from "../components/contact";
import Tiles from "../containers/tiles";
import { useRecoilState } from "recoil";
import { urlState } from "../atoms/urlState";

export default function Home({ aboutMe, resume, projects }) {
  const [url, setUrl] = useRecoilState(urlState);

  setUrl(resume[0]?.resumeUrl);

  return (
    <>
      <Head>
        <title>Home | S - N Portfolio</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Banner resume={resume} />
      <Tiles projects={projects} />
      <About about={aboutMe} />
      <Contact />
    </>
  );
}

export async function getStaticProps() {
  const aboutMe = await client.fetch(groq`
      *[_type == "aboutMe"]
      {
        description,
      }
    `);

  const resume = await client.fetch(groq`
      *[_type == "resume"]
      {
        "resumeUrl": resumeDoc.asset->url,
      }
    `);

  const projects = await client.fetch(groq`
      *[_type == "project"]
      {
        title,
        description,
        mainImage,
        projectLink,
        reportLink,
        viewLink
      }
    `);

  return {
    props: {
      aboutMe,
      resume,
      projects,
    },
  };
}
