/* eslint-disable @next/next/no-img-element */
import Head from "next/head";
import About from "../components/about";
import Banner from "../components/banner";
import Contact from "../components/contact";
import Tiles from "../containers/tiles";

export default function Home() {
  return (
    <>
      <Head>
        <title>Home | S - N Portfolio</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Banner />
      <Tiles />
      <About />
      <Contact />
    </>
  );
}
